{
 "title": "Service overview",
 "tags": [ "main" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "up{instance_type='service'}" } }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{instance='$instance'}" }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(nginx_http_response_count_total{instance='$instance',status=~'...'}[24h])))"
    }
   ]
  },
  {
   "title": "RP24H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(floor(sum(increase(nginx_http_response_count_total{status=~'...', instance='$instance'}[24h]))))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(floor(sum(increase(nginx_http_response_count_total{instance='$instance',status=~'2..'}[24h]))))",
     "legendFormat": "2xx"
    },
    {
     "expr": "(floor(sum(increase(nginx_http_response_count_total{instance='$instance',status=~'3..'}[24h]))))",
     "legendFormat": "3xx"
    },
    {
     "expr": "(floor(sum(increase(nginx_http_response_count_total{instance='$instance',status=~'4..'}[24h]))))",
     "legendFormat": "4xx"
    },
    {
     "expr": "(floor(sum(increase(nginx_http_response_count_total{instance='$instance',status=~'5..'}[24h]))))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, sum by (le) (rate(nginx_http_upstream_time_seconds_hist_bucket{instance='$instance',status='200'}[24h])))) * 100",
     "legendFormat": "95th"
    },
    {
     "expr": "(histogram_quantile(0.90, sum by (le) (rate(nginx_http_upstream_time_seconds_hist_bucket{instance='$instance',status='200'}[24h])))) * 100",
     "legendFormat": "90th"
    },
    {
     "expr": "(histogram_quantile(0.75, sum by (le) (rate(nginx_http_upstream_time_seconds_hist_bucket{instance='$instance',status='200'}[24h])))) * 100",
     "legendFormat": "75th"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "(sum(rate(nginx_http_response_count_total{instance='$instance',status=~'...'}[1m])))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "(floor(sum(increase(nginx_http_response_count_total{instance='$instance',status=~'2..'}[1m]))))",
     "legendFormat": "2xx"
    },
    {
     "expr": "(floor(sum(increase(nginx_http_response_count_total{instance='$instance',status=~'3..'}[1m]))))",
     "legendFormat": "3xx"
    },
    {
     "expr": "(floor(sum(increase(nginx_http_response_count_total{instance='$instance',status=~'4..'}[1m]))))",
     "legendFormat": "4xx"
    },
    {
     "expr": "(floor(sum(increase(nginx_http_response_count_total{instance='$instance',status=~'5..'}[1m]))))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "4xx Destribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "(floor(sum by (status) (increase(nginx_http_response_count_total{instance='$instance',status=~'4..'}[1m]))))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "5xx Destribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "(floor(sum by (status) (increase(nginx_http_response_count_total{instance='$instance',status=~'5..'}[1m]))))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "(histogram_quantile(0.99, sum by (le) (rate(nginx_http_upstream_time_seconds_hist_bucket{instance='$instance',status='200'}[1m]))) * 1000)",
     "legendFormat": "99th"
    },
    {
     "expr": "(histogram_quantile(0.95, sum by (le) (rate(nginx_http_upstream_time_seconds_hist_bucket{instance='$instance',status='200'}[1m]))) * 1000)",
     "legendFormat": "95th"
    },
    {
     "expr": "(histogram_quantile(0.90, sum by (le) (rate(nginx_http_upstream_time_seconds_hist_bucket{instance='$instance',status='200'}[1m]))) * 1000)",
     "legendFormat": "90th"
    },
    {
     "expr": "(histogram_quantile(0.75, sum by (le) (rate(nginx_http_upstream_time_seconds_hist_bucket{instance='$instance',status='200'}[1m]))) * 1000)",
     "legendFormat": "75th"
    },
    {
     "expr": "(histogram_quantile(0.50, sum by (le) (rate(nginx_http_upstream_time_seconds_hist_bucket{instance='$instance',status='200'}[1m]))) * 1000)",
     "legendFormat": "50th"
    }
   ]
  }
 ]
}