FROM grafana/grafana:8.3.0

# запрет регистрации новых пользователей
ENV GF_USERS_ALLOW_SIGN_UP=false 
# доступ пользователям с правами на просмотр к странице Explore, 
# а также к выполнению временного редактирования дашбордов
ENV GF_USERS_VIEWERS_CAN_EDIT=true
